import Head from 'next/head'
import { signOut } from 'next-auth/react';
export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>LinkedIn</h1>
      <button onClick={signOut}>Sign out</button>
    </div>
  )
}
